In [11]:
import pandas as pd

In [12]:
df = pd.read_csv("diabetes.csv")
df

     Pregnancies  Glucose  BloodPressure  SkinThickness
0              6      148             72             35
1              1       85             66             29
2              8      183             64              0
3              1       89             66             23
4              0      137             40             35
..           ...      ...            ...            ...
763           10      101             76             48
764            2      122             70             27
765            5      121             72             23
766            1      126             60              0
767            1       93             70             31

[768 rows x 4 columns]

In [13]:
df.isnull().sum()

Pregnancies      0
Glucose          0
BloodPressure    0
SkinThickness    0
dtype: int64

In [15]:
df.pivot_table(index="Pregnancies")

             BloodPressure     Glucose  SkinThickness
Pregnancies
0                67.153153  123.000000      22.270270
1                67.792593  112.748148      24.437037
2                63.252427  110.796117      21.601942
3                66.586667  123.586667      20.080000
4                70.029412  125.117647      15.882353
5                76.210526  118.859649      17.385965
6                68.420000  120.800000      17.640000
7                70.777778  136.444444      20.288889
8                75.184211  131.736842      17.315789
9                77.892857  131.392857      20.892857
10               70.208333  120.916667      15.708333
11               74.181818  126.454545      21.727273
12               76.333333  113.555556      27.111111
13               73.800000  125.500000      17.300000
14               70.000000  137.500000      27.500000
15               70.000000  136.000000      32.000000
17               72.000000  163.000000      41.000000

In [17]:
df.pivot_table(index="Pregnancies", columns="SkinThickness")

              BloodPressure                                                \
SkinThickness            0     7     8     10    11         12         13
Pregnancies
0                 50.531250   NaN   NaN  52.0   NaN        NaN  56.000000
1                 66.687500   NaN  64.0  54.0  70.0  69.333333  63.200000
2                 54.217391   NaN   NaN  62.0   NaN        NaN  65.000000
3                 57.777778   NaN   NaN  50.0  69.0  90.000000  56.666667
4                 65.333333   NaN   NaN   NaN  88.0  64.666667        NaN
5                 77.160000   NaN   NaN   NaN   NaN        NaN        NaN
6                 68.047619  90.0   NaN   NaN   NaN        NaN        NaN
7                 63.000000   NaN   NaN   NaN   NaN        NaN        NaN
8                 72.555556   NaN   NaN   NaN   NaN        NaN        NaN
9                 72.666667   NaN   NaN   NaN   NaN        NaN        NaN
10                62.666667   NaN   NaN   NaN   NaN        NaN        NaN
11                64.000000   NaN   NaN   NaN   NaN        NaN        NaN
12                80.000000  62.0   NaN   NaN   NaN        NaN        NaN
13                81.200000   NaN   NaN   NaN   NaN        NaN        NaN
14                      NaN   NaN   NaN   NaN   NaN        NaN        NaN
15                      NaN   NaN   NaN   NaN   NaN        NaN        NaN
17                      NaN   NaN   NaN   NaN   NaN        NaN        NaN

                                 ... Glucose                              \
SkinThickness    14    15    16  ...      48     49     50     51     52
Pregnancies                      ...
0              75.0  82.0  80.0  ...     NaN    NaN    NaN    NaN    NaN
1              64.0  63.0  50.0  ...   120.0  172.0  103.5  122.0   86.0
2              67.0  62.0  64.0  ...     NaN    NaN  112.0    NaN  100.0
3               NaN  74.0  80.0  ...   173.0  129.0    NaN    NaN    NaN
4              70.0  78.0   NaN  ...     NaN    NaN    NaN    NaN    NaN
5               NaN   NaN   NaN  ...     NaN    NaN    NaN    NaN    NaN
6               NaN   NaN   NaN  ...     NaN    NaN    NaN    NaN    NaN
7               NaN  88.0   NaN  ...     NaN  129.0    NaN    NaN    NaN
8               NaN   NaN   NaN  ...     NaN    NaN    NaN    NaN    NaN
9               NaN  85.0   NaN  ...     NaN    NaN    NaN    NaN    NaN
10              NaN   NaN   NaN  ...   124.5    NaN    NaN    NaN    NaN
11              NaN   NaN   NaN  ...     NaN    NaN    NaN    NaN    NaN
12              NaN   NaN   NaN  ...     NaN    NaN    NaN    NaN    NaN
13              NaN   NaN   NaN  ...     NaN    NaN    NaN    NaN    NaN
14              NaN   NaN   NaN  ...     NaN    NaN    NaN    NaN    NaN
15              NaN   NaN   NaN  ...     NaN    NaN    NaN    NaN    NaN
17              NaN   NaN   NaN  ...     NaN    NaN    NaN    NaN    NaN


SkinThickness     54     56     60     63     99
Pregnancies
0              147.0  162.0  100.0  180.0    NaN
1                NaN    NaN    NaN    NaN    NaN
2                NaN    NaN    NaN    NaN  197.0
3                NaN    NaN    NaN    NaN    NaN
4                NaN    NaN    NaN    NaN    NaN
5                NaN    NaN    NaN    NaN    NaN
6                NaN    NaN    NaN    NaN    NaN
7                NaN    NaN    NaN    NaN    NaN
8                NaN    NaN    NaN    NaN    NaN
9                NaN    NaN    NaN    NaN    NaN
10               NaN    NaN    NaN    NaN    NaN
11               NaN    NaN    NaN    NaN    NaN
12               NaN    NaN    NaN    NaN    NaN
13             106.0    NaN    NaN    NaN    NaN
14               NaN    NaN    NaN    NaN    NaN
15               NaN    NaN    NaN    NaN    NaN
17               NaN    NaN    NaN    NaN    NaN

[17 rows x 102 columns]

In [19]:
df.pivot_table(index="Pregnancies", columns="SkinThickness", aggfunc="min")

              BloodPressure                                                  \
SkinThickness            0     7     8     10    11    12    13    14    15
Pregnancies
0                       0.0   NaN   NaN  52.0   NaN   NaN  56.0  68.0  82.0
1                       0.0   NaN  60.0  50.0  56.0  62.0  54.0  64.0  50.0
2                       0.0   NaN   NaN  62.0   NaN   NaN  62.0  54.0  52.0
3                       0.0   NaN   NaN  50.0  58.0  90.0  44.0   NaN  68.0
4                       0.0   NaN   NaN   NaN  88.0  60.0   NaN  70.0  76.0
5                      48.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
6                       0.0  90.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN
7                       0.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN  88.0
8                       0.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
9                      52.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN  85.0
10                      0.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
11                      0.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
12                     80.0  62.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN
13                     60.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
14                      NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
15                      NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
17                      NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

                     ... Glucose                                            \
SkinThickness    16  ...      48     49     50     51     52     54     56
Pregnancies          ...
0              80.0  ...     NaN    NaN    NaN    NaN    NaN  147.0  162.0
1              50.0  ...   120.0  172.0   71.0  122.0   86.0    NaN    NaN
2              58.0  ...     NaN    NaN  112.0    NaN  100.0    NaN    NaN
3              74.0  ...   173.0  129.0    NaN    NaN    NaN    NaN    NaN
4               NaN  ...     NaN    NaN    NaN    NaN    NaN    NaN    NaN
5               NaN  ...     NaN    NaN    NaN    NaN    NaN    NaN    NaN
6               NaN  ...     NaN    NaN    NaN    NaN    NaN    NaN    NaN
7               NaN  ...     NaN  129.0    NaN    NaN    NaN    NaN    NaN
8               NaN  ...     NaN    NaN    NaN    NaN    NaN    NaN    NaN
9               NaN  ...     NaN    NaN    NaN    NaN    NaN    NaN    NaN
10              NaN  ...   101.0    NaN    NaN    NaN    NaN    NaN    NaN
11              NaN  ...     NaN    NaN    NaN    NaN    NaN    NaN    NaN
12              NaN  ...     NaN    NaN    NaN    NaN    NaN    NaN    NaN
13              NaN  ...     NaN    NaN    NaN    NaN    NaN  106.0    NaN
14              NaN  ...     NaN    NaN    NaN    NaN    NaN    NaN    NaN
15              NaN  ...     NaN    NaN    NaN    NaN    NaN    NaN    NaN
17              NaN  ...     NaN    NaN    NaN    NaN    NaN    NaN    NaN


SkinThickness     60     63     99
Pregnancies
0              100.0  180.0    NaN
1                NaN    NaN    NaN
2                NaN    NaN  197.0
3                NaN    NaN    NaN
4                NaN    NaN    NaN
5                NaN    NaN    NaN
6                NaN    NaN    NaN
7                NaN    NaN    NaN
8                NaN    NaN    NaN
9                NaN    NaN    NaN
10               NaN    NaN    NaN
11               NaN    NaN    NaN
12               NaN    NaN    NaN
13               NaN    NaN    NaN
14               NaN    NaN    NaN
15               NaN    NaN    NaN
17               NaN    NaN    NaN

[17 rows x 102 columns]

In [20]:
df.pivot_table(index="Pregnancies", columns="SkinThickness", aggfunc="sum", margins="True")

              BloodPressure                                                   \
SkinThickness             0      7      8     10     11     12     13     14
Pregnancies
0                    1617.0    NaN    NaN   52.0    NaN    NaN   56.0  150.0
1                    1067.0    NaN  128.0  108.0  210.0  208.0  316.0   64.0
2                    1247.0    NaN    NaN   62.0    NaN    NaN  130.0  134.0
3                    1040.0    NaN    NaN   50.0  138.0   90.0  170.0    NaN
4                    1764.0    NaN    NaN    NaN   88.0  194.0    NaN   70.0
5                    1929.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6                    1429.0   90.0    NaN    NaN    NaN    NaN    NaN    NaN
7                    1008.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN
8                    1306.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN
9                     654.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN
10                    752.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN
11                    256.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN
12                     80.0   62.0    NaN    NaN    NaN    NaN    NaN    NaN
13                    406.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN
14                      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
15                      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
17                      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
All                 14555.0  152.0  128.0  272.0  436.0  492.0  672.0  418.0

                              ... Glucose                                     \
SkinThickness      15     16  ...      49     50     51     52     54     56
Pregnancies                   ...
0                82.0   80.0  ...     NaN    NaN    NaN    NaN  147.0  162.0
1               252.0   50.0  ...   172.0  207.0  122.0   86.0    NaN    NaN
2               124.0  128.0  ...     NaN  112.0    NaN  100.0    NaN    NaN
3               222.0  160.0  ...   129.0    NaN    NaN    NaN    NaN    NaN
4               156.0    NaN  ...     NaN    NaN    NaN    NaN    NaN    NaN
5                 NaN    NaN  ...     NaN    NaN    NaN    NaN    NaN    NaN
6                 NaN    NaN  ...     NaN    NaN    NaN    NaN    NaN    NaN
7                88.0    NaN  ...   129.0    NaN    NaN    NaN    NaN    NaN
8                 NaN    NaN  ...     NaN    NaN    NaN    NaN    NaN    NaN
9                85.0    NaN  ...     NaN    NaN    NaN    NaN    NaN    NaN
10                NaN    NaN  ...     NaN    NaN    NaN    NaN    NaN    NaN
11                NaN    NaN  ...     NaN    NaN    NaN    NaN    NaN    NaN
12                NaN    NaN  ...     NaN    NaN    NaN    NaN    NaN    NaN
13                NaN    NaN  ...     NaN    NaN    NaN    NaN  106.0    NaN
14                NaN    NaN  ...     NaN    NaN    NaN    NaN    NaN    NaN
15                NaN    NaN  ...     NaN    NaN    NaN    NaN    NaN    NaN
17                NaN    NaN  ...     NaN    NaN    NaN    NaN    NaN    NaN
All            1009.0  418.0  ...   430.0  319.0  122.0  186.0  253.0  162.0


SkinThickness     60     63     99    All
Pregnancies
0              100.0  180.0    NaN  13653
1                NaN    NaN    NaN  15221
2                NaN    NaN  197.0  11412
3                NaN    NaN    NaN   9269
4                NaN    NaN    NaN   8508
5                NaN    NaN    NaN   6775
6                NaN    NaN    NaN   6040
7                NaN    NaN    NaN   6140
8                NaN    NaN    NaN   5006
9                NaN    NaN    NaN   3679
10               NaN    NaN    NaN   2902
11               NaN    NaN    NaN   1391
12               NaN    NaN    NaN   1022
13               NaN    NaN    NaN   1255
14               NaN    NaN    NaN    275
15               NaN    NaN    NaN    136
17               NaN    NaN    NaN    163
All            100.0  180.0  197.0  92847

[18 rows x 104 columns]